blasbase/urls.py
from django.conf.urls import patterns, include, url
from blasbase.views import PersonList, PersonDetail, PersonAdd, PersonChange

urlpatterns = patterns(
    '',
    #url(r'^$', 'blasbase.views.index'),
    url(r'^$', PersonList.as_view()),
    url(r'^person/(?P<pk>\d+)/$', PersonDetail.as_view(), name='person_detail'),
    url(r'^person/(?P<pk>\d+)/change/$', PersonChange.as_view(template_name_suffix='_change')),
    url(r'^person/add/$', PersonAdd.as_view(template_name_suffix='_add')),
    #url(r'^person/(?P<user>\d+)/edit/$', 'blasbase.views.person_edit'),
    #url(r'^person/(?P<user>\d+)/delete/$', 'blasbase.views.person_delete'),
    
    #url(r'section/$', 'blasbase.views.section_list'),
    #url(r'section/(?P<section>)/$', 'blasbase.views.section_detail'),
)

blasfisk/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

from cms.sitemaps import CMSSitemap

from django.contrib import admin

admin.autodiscover()

# URL:er som hamnar under roten
urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^login/$', 'django.contrib.auth.views.login'),

    url(r'^400/$', TemplateView.as_view(template_name='400.html')),  # Test för 400-sidan
    url(r'^403/$', TemplateView.as_view(template_name='403.html')),  # Test för 403-sidan
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),  # Test för 404-sidan
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),  # Test för 500-sidan
    url(r'^test/$', TemplateView.as_view(template_name='test.html')),

    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
)

# URL:er som hamnar under respektive språkkod, typ /sv/
urlpatterns += i18n_patterns(
    '',
    url(r'^', include('cms.urls')),  # <--------- include the django cms urls via i18n_patterns
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    ) + urlpatterns

events/urls.py
from django.conf.urls import patterns, include, url
from events.views import EventList

urlpatterns = patterns(
    '',
    url(r'^$', EventList.as_view()),
)

blasbase/models.py
# -*- coding: utf-8 -*-
import datetime
from dateutil.relativedelta import relativedelta

from mptt.models import MPTTModel, TreeForeignKey, TreeManager
from django.db import models
from django.db.models.query import QuerySet
from django.db.models import F, Q
from django.contrib.auth.models import (
    BaseUserManager,
    PermissionsMixin,
    AbstractBaseUser,
    Permission
)
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from imagekit.models import ProcessedImageField

from globals import GENDERS, COUNTRIES, CONTACT_TYPES, generate_filename
from blasbase.backends import make_permission_set
from blasbase import validators
from locations.models import AddressMixin




def generate_avatar_filename(instance, filename):
    return generate_filename(instance, filename, 'avatars')


class PhoneNumber(models.Model):
    type = models.CharField(max_length=16, choices=CONTACT_TYPES, default='private', verbose_name=_('type'))
    country = models.CharField(max_length=2, choices=COUNTRIES, default='SE', blank=True, verbose_name=_('country'))
    phone_number = models.CharField(max_length=64, verbose_name=_('phone number'))

    class Meta:
        abstract = True


class EmailAddress(models.Model):
    type = models.CharField(max_length=16, choices=CONTACT_TYPES, default='private', verbose_name=_('type'))
    email_address = models.CharField(max_length=256, verbose_name=_('email address'))

    class Meta:
        abstract = True


class PersonAddress(AddressMixin):
    type = models.CharField(max_length=16, choices=CONTACT_TYPES, default='private', verbose_name=_('type'))
    person = models.ForeignKey('blasbase.Person', related_name='addresses', verbose_name=_('person'))


class PersonEmailAddress(EmailAddress):
    person = models.ForeignKey('blasbase.Person', related_name='email_addresses', verbose_name=_('person'))


class PersonPhoneNumber(PhoneNumber):
    person = models.ForeignKey('blasbase.Person', related_name='phone_numbers', verbose_name=_('person'))


class PersonQuerySetMixin(object):
    def members(self):
        return self.filter(assignments__in=Assignment.objects.memberships()).distinct()

    def active(self):
        """Hämtar personer som är relaterade till aktiva assignments. distinct() tar bort eventuella dubletter."""
        return self.filter(assignments__in=Assignment.objects.active()).distinct()

    def oldies(self):
        """Hämtar personer som är relaterade till utgångna assignments (för att hitta personerna som _varit_ medlemmar)
        och exkluderar sedan personer som har relationer till aktiva dito. distinct() tar bort eventuella dubletter."""
        return self.filter(assignments__in=Assignment.objects.oldies()).exclude(
            assignments__in=Assignment.objects.active()).distinct()

    def others(self):
        return self.exclude(assignments__in=Assignment.objects.memberships()).distinct()


class PersonQuerySet(QuerySet, PersonQuerySetMixin):
    pass


class PersonManager(models.Manager, PersonQuerySetMixin):
    # TODO: Remove when changing to Django 1.7
    def get_queryset(self):
        return PersonQuerySet(model=self.model, using=self._db)


@python_2_unicode_compatible
class Person(models.Model):
    """Lagrar personer (som i människor) och är den datatyp som nästan allt i Blåsbasen kopplas till."""
    first_name = models.CharField(max_length=256, verbose_name=_('first name'))
    nickname = models.CharField(max_length=256, blank=True, verbose_name=_('nickname'))
    last_name = models.CharField(max_length=256, verbose_name=_('last name'),
                                 help_text=_('Feel free to specify earlier last name in parentheses, e.g. Vidner (Eriksson)'))
    gender = models.CharField(max_length=1, choices=GENDERS, blank=True, verbose_name=_('gender'))
    born = models.DateField(blank=True, null=True, verbose_name=_('born'),
                            validators=[validators.date_before_today])
    deceased = models.DateField(blank=True, null=True, verbose_name=_('deceased'),
                                validators=[validators.date_before_today])
    personal_id_number = models.CharField(max_length=4, blank=True, verbose_name=_('personal identification number'),
                                          help_text=_('Last 4 characters in Swedish personal ID number'))
    liu_id = models.CharField(max_length=8, blank=True, verbose_name=_('LiU-ID'))

    about = models.TextField(blank=True, verbose_name=_('about'))

    special_diets = models.ManyToManyField('SpecialDiet', related_name='people', blank=True, null=True, verbose_name=_('special diets'))
    special_diets_extra = models.CharField(max_length=256, blank=True, verbose_name=_('special diets comments'))

    functions = models.ManyToManyField('Function', through='Assignment', verbose_name=_('functions'))

    last_updated = models.DateTimeField(auto_now=True, verbose_name=_('last updated'))
    old_database_id = models.IntegerField(blank=True, null=True)
    objects = PersonManager()

    class Meta:
        ordering = ['first_name', 'last_name', 'nickname']
        verbose_name = _('person')
        verbose_name_plural = _('people')

    def __str__(self):
        return self.get_full_name()

    def clean(self):
        cleaned_data = super(Person, self).clean()

        # Validera endast om både födelse- och dödsdatum angetts.
        if self.born and self.deceased:
            validators.datetime_before_datetime(self.born, self.deceased, _('Decease date must be after birth date.'))
        return cleaned_data

    @property
    def age(self):
        if self.born and not self.deceased:
            return relativedelta(datetime.date.today(), self.born)
        elif self.born and self.deceased:
            return relativedelta(self.deceased, self.born)
        return None

    @property
    def memberships(self):
        return self.assignments.memberships()

    @property
    def engagements(self):
        return self.assignments.engagements()

    def get_primary_avatar(self):
        return self.avatars.get(primary=True)

    def get_secondary_avatars(self):
        return self.avatars.exclude(primary=True)

    # Används internt av Django
    def get_full_name(self):
        if self.nickname:
            return u'{0} "{1}" {2}'.format(self.first_name, self.nickname, self.last_name)  # Leif "Pappa Blås" Holm

        return u'{0} {1}'.format(self.first_name, self.last_name)  # Leif Holm

    # Används internt av Django
    def get_short_name(self):
        if self.nickname:
            return self.nickname  # Pappa Blås

        return u'{0} {1}'.format(self.first_name, self.last_name[0])  # Leif H

    @property
    def membership_start(self):
        """Hämtar alla assignments som innebär medlemsskap och som inte är provmedlemsskap,
        sorterar stigande på startdatum, tar det första objektet och ger detta objekts startdatum"""
        try:
            return self.assignments.memberships().first().start_date
        except AttributeError:
            # Om man inte har något assignment som passar i filtret alls måste vi hantera det felet på något vis. Då
            # returnerar vi None istället.
            return None

    @property
    def membership_end(self):
        a = self.assignments.memberships().order_by('end_date')

        # Om man inte har några sådana assignments eller om någon är pågående returnerar vi None
        if not a or a.filter(pk__in=Assignment.objects.active()):
            return None

        # Annars tar vi det sista objektet och ger dess slutdatum
        return a.last().end_date

    full_name = property(get_full_name)
    short_name = property(get_short_name)
    primary_avatar = property(get_primary_avatar)
    secondary_avatars = property(get_secondary_avatars)


@python_2_unicode_compatible
class Avatar(models.Model):
    picture = ProcessedImageField(upload_to=generate_avatar_filename, verbose_name=_('picture'))
    person = models.ForeignKey('Person', related_name='avatars', verbose_name=_('person'))
    primary = models.BooleanField(default=True, verbose_name=_('primary'))

    class Meta:
        ordering = ['primary', 'id']

    def __str__(self):
        return u'{0}: {1}'.format(self.person.short_name, self.id)

    def save(self, *args, **kwargs):
        # Sparar objektet som vanligt
        super(Avatar, self).save(*args, **kwargs)

        # Hämtar alla avatarer tillhörande samma person som aktuellt objekt
        avatars = self.person.avatar_set

        if self.primary:
            # Tar bort primary från alla avatarer tillhörande samma människa. Exkluderar aktuellt objekt om det redan finns.
            avatars.exclude(pk=self.pk).update(primary=False)

        else:
            # Om det inte finns någon avatar tillhörande denna person som är märkt som primär...
            if not avatars.filter(primary=True).exists():
                # ...välj den senast tillagda avataren och välj som primär, välj bort aktuellt objekt om det finns
                a = avatars.exclude(pk=self.pk).order_by('-pk')[0]
                a.primary = True
                a.save()

    def get_url(self):
        """Hämtar (publik) URL till bilden"""
        return self.picture.url

    def get_path(self):
        """Hämtar sökväg (i filsystemet) till bilden"""
        return self.picture._get_path()

    url = property(get_url)
    path = property(get_path)


class UserManager(BaseUserManager):
    """Plankat från Djangos dokumentation. Används för Blåsbasens användarmodell."""

    def create_user(self, username, password):
        if not username:
            raise ValueError('Users must have a username')

        if not password:
            raise ValueError('Users must have a password')

        # TODO: Fixa nåt snyggare
        person = Person(first_name=u'Niklas', last_name=u'Namnlös')
        person.save()

        user = self.model(
            person=person,

blasbase/views.py
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.shortcuts import render
from django.http import Http404
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from blasbase.models import Person
from globals import COUNTRIES
from django.utils.translation import ugettext_lazy as _


class PersonList(ListView):
    context_object_name = 'people'

    def simple_search(self, queryset, name):
        return queryset.filter(Q(first_name__icontains=name) |
                               Q(nickname__icontains=name) |
                               Q(last_name__icontains=name))

    def get_queryset(self):
        queryset = Person.objects.all()
        # Sökning
        if self.request.GET.get('search') == 's':
            queryset = self.simple_search(queryset, self.request.GET.get('name'))

        elif self.request.GET.get('search') == 'a':
            queryset = (self.simple_search(queryset, self.request.GET.get('name')).
                        filter(gender__contains=self.request.GET.get('gender')))

            if not self.request.GET.get('w_login'):
                queryset = queryset.exclude(user=True)

            if not self.request.GET.get('wo_login'):
                queryset = queryset.exclude(user=None)

        if self.request.GET.get('sort'):
            return queryset.order_by(self.request.GET.get('sort'))
        else:
            return queryset

    def get_context_data(self, **kwargs):
        context = super(PersonList, self).get_context_data(**kwargs)

        # Här definieras alla filter. Skriv ett nytt här så genereras det HTML automatiskt.
        # Om det behövs fler sätt att filtrera personer på, rekommenderar jag att man skriver en metod till PersonManager.
        # Det är så jag gjort befintliga filter, så kör man bara en .filter(pk__in=Person.objects.hokuspokus()).
        context['filters'] = []
        context['filters'].append({'id': 'members',
                                   'name': _('Members'),
                                   'default': True,  # Avgör vilken flik som är förvald. Får bara finnas på ett filter.
                                   'content': context['people'].filter(pk__in=Person.objects.members())})
        context['filters'].append({'id': 'active',
                                   'name': _('Active'),
                                   'content': context['people'].filter(pk__in=Person.objects.active())})
        context['filters'].append({'id': 'oldies',
                                   'name': _('Oldies'),
                                   'content': context['people'].filter(pk__in=Person.objects.oldies())})
        context['filters'].append({'id': 'others',
                                   'name': _('Others'),
                                   'content': context['people'].filter(pk__in=Person.objects.others())})
        context['filters'].append({'id': 'all',
                                   'name': _('Everybody'),
                                   'content': context['people']})

        #context['sections'] = Section.objects.all().order_by('name')
        #context['posts'] = Post.objects.all().order_by('name').order_by('section')
        context['countries'] = COUNTRIES

        if self.request.GET:
            # Hämtar alla GET-parametrar men tar bort sort och tab. Används av "sorterings-väljaren" för att behålla alla sökparametrar.

            #GET är immutable, så vi kopierar den istället
            get_params = self.request.GET.copy()

            if 'sort' in get_params:
                get_params.__delitem__('sort')

            if 'tab' in get_params:
                get_params.__delitem__('tab')

            context['search_params'] = get_params

        return context


class PersonDetail(DetailView):
    model = Person

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PersonDetail, self).get_context_data(**kwargs)

        context['memberships'] = context['person'].assignments.memberships(all=True)
        context['engagements'] = context['person'].assignments.engagements(all=True)
        return context


class PersonAdd(CreateView):
    model = Person


class PersonChange(UpdateView):
    model = Person

blasfisk/templates/blasbase/person_list.html
{% extends CMS_TEMPLATE %}
{% load cms_tags %}

{% block content %}
<div class="page-header page-title">
    <div class="container">
        <h1>Blåsbasen <small>Personregistret</small></h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <ul class="nav nav-pills nav-justified">
                {% for f in filters %}
                <li{% if request.GET.tab == f.id or not request.GET.tab and f.default %} class="active"{% endif %}>
                    <a href="#{{ f.id }}" data-toggle="tab">{{ f.name }} <span class="badge">{{ f.content.count }}</span></a>
                    </li>
                    {% endfor %}
            </ul>

            <div class="tab-content">
                {% for f in filters %}
                <div class="tab-pane {% if request.GET.tab == f.id or not request.GET.tab and f.default %}active{% endif %}" id="{{ f.id }}">
                    {% if f.content %}
                    <table class="table table-hover">
                        <tr>
                            {% if perms.blasbasen.change_person %}
                            <th></th>
                            {% endif %}
                            <th>Förnamn<a href="?sort=first_name&tab={{ f.id }}&{{ search_params.urlencode }}" class="pull-right"><span class="fa fa-sort-alpha-asc"></span></a></th>
                            <th>Blåsnamn<a href="?sort=nickname&tab={{ f.id }}&{{ search_params.urlencode }}" class="pull-right"><span class="fa fa-sort-alpha-asc"></span></a></th>
                            <th>Efternamn<a href="?sort=last_name&tab={{ f.id }}&{{ search_params.urlencode }}" class="pull-right"><span class="fa fa-sort-alpha-asc"></span></a></th>
                            <th>Sektion</th>
                            <th>Antagen</th>
                            <th>Gamling</th>
                        </tr>

                        {% for person in f.content %}
                        <tr>
                            {% if perms.blasbasen.change_person %}
                            <td><a href="{{ person.pk }}/change/"><span class="fa fa-lg fa-edit"></span></a></td>
                            {% endif %}
                            <td><a href="{{ person.pk }}/">{{ person.first_name }}</a></td>
                            <td><a href="{{ person.pk }}/">{{ person.nickname }}</a></td>
                            <td><a href="{{ person.pk }}/">{{ person.last_name }}</a></td>
                            <td>#TODO</td>
                            <td>{{ person.start.year }}</td>
                            <td>{{ person.end.year }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% else %}
                    <p>Inga träffar.</p>
                    {% endif %}
                    
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-3">
            <form role="form" method="get" action=".">
                <input type="hidden" name="search" value="s">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="name" value="{{ request.GET.name }}" placeholder="Snabbsök på namn">
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">
                                <span class="fa fa-search"></span>
                            </button> </span>

                    </div>
                </div>
            </form>
            {% if request.GET.search %}
            <div class="form-group">
                <a href="." class="form-control btn btn-warning"><span class="fa fa-times"></span> Återställ och visa alla</a>
            </div>
            {% endif %}
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#advancedsearch"> Avancerad sökning </a></h4>
                    </div>
                    <div id="advancedsearch_" class="panel-collapse collapse">

                        <div class="panel-body">

                        </div>

                    </div>
                    <div id="advancedsearch" class="list-group panel-collapse collapse{% if request.GET.search = 'a' %} in{% endif %}">
                        <form role="form" method="get" action=".">
                            <input type="hidden" name="search" value="a">
                            <div class="list-group-item">

                                <div class="form-group">
                                    <label for="name">Namn</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{ request.GET.name }}" placeholder="Namn">
                                </div>
                                <div class="form-group">
                                    <label for="gender">Kön</label>
                                    <select class="form-control" id="gender" name="gender">
                                        <option {% if request.GET.gender = '' %}selected=""{% endif %} value="">Vilket som</option>
                                        <option {% if request.GET.gender = 'f' %}selected=""{% endif %} value="f">Kvinna</option>
                                        <option {% if request.GET.gender = 'm' %}selected=""{% endif %} value="m">Man</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="city">Stad</label>
                                    <input type="text" class="form-control" id="city" name="city" value="{{ request.GET.city }}" placeholder="Stad">
                                    <p class="help-block">
                                        Använd kommatecken för att ange flera
                                    </p>
                                </div>
                                <div class="form-group">
                                    <label for="countries">Länder</label>
                                    <select multiple class="form-control" id="countries" name="country">
                                        {% for c in countries %}
                                        <option {% if request.GET.country = c.0 %}selected=""{% endif %} value="{{ c.0 }}">{{ c.1 }}</option>
                                        {% endfor %}

                                    </select>
                                    <p class="help-block">
                                        Tips: Använd Ctrl eller Cmd (⌘)
                                    </p>
                                </div>
                            </div>
                            <div class="list-group-item">
                                <h5 class="list-group-item-heading">Medlemsskap</h5>
                                <div class="form-group">
                                    <label for="sections">Sektioner</label>
                                    <select multiple class="form-control" id="sections" name="section">
                                        {% for s in sections %}
                                        <option value="{{ s.pk }}">{{ s }}</option>
                                        {% endfor %}
                                    </select>
                                    <p class="help-block">
                                        Tips: Använd Ctrl eller Cmd (⌘)
                                    </p>
                                </div>
                                <div class="form-group">
                                    <label for="posts">Poster</label>
                                    <select multiple class="form-control" id="posts" name="post">
                                        {% for p in posts %}
                                        <option value="{{ p.pk }}">{{ p }}</option>
                                        {% endfor %}
                                    </select>
                                    <p class="help-block">
                                        Tips: Använd Ctrl eller Cmd (⌘)
                                    </p>
                                </div>
                            </div>
                            <div class="list-group-item">
                                <h5 class="list-group-item-heading">Visa</h5>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" {% if request.GET.w_login or not request.GET.search = 'a' %}checked="checked"{% endif %} name="w_login">
                                        Personer med inloggningskonto </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" {% if request.GET.wo_login or not request.GET.search = 'a' %}checked="checked"{% endif %} name="wo_login">
                                        Personer utan inloggningskonto </label>
                                </div>
                            </div>
                        
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-primary btn-sm form-control">
                                <span class="fa fa-search"></span> Sök
                            </button>
                        </div>
                        </form>
                    </div>

                </div>
            </div>
            <h3>Åtgärder</h3>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#export"> Exportera och visa</a></h4>
                    </div>
                    <div class="panel-body panel-collapse collapse"></div>
                    <div id="export" class="list-group panel-collapse collapse">
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-link"></span> Permalänk</a>
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-globe"></span> Visa på Google Maps</a>
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-file-o"></span> Exportera vCard</a>
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-file-text-o"></span> Exportera CSV</a>
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-file-pdf-o"></span> Exportera PDF</a>
                    </div>

                </div>
                {% if perms.blasbasen.add_person or perms.blasbasen.change_person or perms.blasbasen.delete_person %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#admin"> Administrera </a></h4>
                    </div>
                    <div class="panel-body panel-collapse collapse"></div>
                    <div id="admin" class="list-group panel-collapse collapse">
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-user"></span> Lägg till person</a>
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-users"></span> Lägg till sektion</a>
                        <a href="" class="list-group-item"><span class="fa fa-fw fa-graduation-cap"></span> Lägg till post</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}